# Generated by Django 5.1.3 on 2024-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=12)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('Course', models.CharField(max_length=50)),
            ],
        ),
    ]
