# Generated by Django 5.1.3 on 2024-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_curd_app', '0003_alter_studentlist_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
