# Generated by Django 5.1.6 on 2025-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
    ]
